### PR TITLE
EOS-13608: Update build script to fetch current branch of cortx-posix and and pull same branch for other repos

### PR DESCRIPTION
**Pull request by Shreya-18**
## Problem Statement
https://jts.seagate.com/browse/EOS-13608
The branch checked out of cortx-posix should be used to fetch all the other git repos.

## Problem Description

Currently, in the cortx-posix build script, the bootstrap function has a variable that explicitly specifies the branch-name as "dev" and git clones all the repos with the same branch.

## Solution
Fetch branch name of current cortx-posix.  Use the same branch name to pull all the other git repos present inside cortx-posix.

### CODE REVIEW

**Review by s-arya — COMMENTED** [review]
Question: Currently there are be Cortx_1.0.xxx branches for cortx-posix repository, but these branches are not present for all the other NFS sub repos.  Will the script pass if devops team creates a cortx-1.0.xxx build by running this script?

**Comment by Shreya-18** [comment]
> Question: Currently there are Cortx_1.0.xxx branches for cortx-posix repository, but these branches are not present for all the other NFS sub repos. Will the script pass if devops team creates a cortx-1.0.xxx build by running this script?

To answer your question, the script will say `fatal: Remote branch Cortx_1.0.xxx not found in upstream origin` (output of git command) for the NFS sub repos.

Mostly the use-case of `bootstrap` is at the beginning of the script to clone all repos which are not present inside the repo. Moreover, it won't pull the repos if they already exist. So didn't handle this case.

But if you want, I can make a change which will by default fetch `main` branch if any other branch (except main and stable) is specified.

**Comment by sachinpunadikar** [comment]
> > Question: Currently there are Cortx_1.0.xxx branches for cortx-posix repository, but these branches are not present for all the other NFS sub repos. Will the script pass if devops team creates a cortx-1.0.xxx build by running this script?
> 
> To answer your question, the script will say `fatal: Remote branch Cortx_1.0.xxx not found in upstream origin` (output of git command) for the NFS sub repos.
> 
> Mostly the use-case of `bootstrap` is at the beginning of the script to clone all repos which are not present inside the repo. Moreover, it won't pull the repos if they already exist. So didn't handle this case.
> 
> But if you want, I can make a change which will by default fetch `main` branch if any other branch (except main and stable) is specified.
> @sachinpunadikar What do you say? How should we handle this case?

In my opinion, let the bootstrap fail in case there is no matching branch in other repos. This will ensure that we have required branch created in all the repos. No need to switch over to main or stable branch.

**Comment by s-arya** [comment]
> > > Question: Currently there are Cortx_1.0.xxx branches for cortx-posix repository, but these branches are not present for all the other NFS sub repos. Will the script pass if devops team creates a cortx-1.0.xxx build by running this script?
> > 
> > 
> > To answer your question, the script will say `fatal: Remote branch Cortx_1.0.xxx not found in upstream origin` (output of git command) for the NFS sub repos.
> > Mostly the use-case of `bootstrap` is at the beginning of the script to clone all repos which are not present inside the repo. Moreover, it won't pull the repos if they already exist. So didn't handle this case.
> > But if you want, I can make a change which will by default fetch `main` branch if any other branch (except main and stable) is specified.
> > @sachinpunadikar What do you say? How should we handle this case?
> 
> In my opinion, let the bootstrap fail in case there is no matching branch in other repos. This will ensure that we have required branch created in all the repos. No need to switch over to main or stable branch.

Okay. I'll approve the PR.

**Review by s-arya — APPROVED** [review]
LGTM

**Pull request merged**
